### 게시글 생성
POST /localhost:8080/posts
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "createdBy": "minJiKim"
}

### 게시글 생성
PUT /localhost:8080/posts/1
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "modifiedBy": "cherHyJung"
}

### 게시글 삭제
DELETE /localhost:8080/posts/1?createdBy=cherHyJung

### 게시글 조회
GET /localhost:8080/posts

### 게시글 상세조회
GET /localhost:8080/posts/1

